import http from "node:http";

// Minimal MCP-style seller server the gateway forwards settled calls to.
// Contract: POST /mcp {"tool": string, "input": object}, GET /healthz.

const port = Number(process.env.EXAMPLE_SERVER_PORT ?? "9090");
const gatewayKey = process.env.GATEWAY_KEY ?? "";

type ToolInput = Record<string, unknown>;

function writeJSON(res: http.ServerResponse, status: number, payload: unknown): void {
  const body = JSON.stringify(payload);
  res.writeHead(status, {
    "Content-Type": "application/json",
    "Content-Length": Buffer.byteLength(body)
  });
  res.end(body);
}

function readBody(req: http.IncomingMessage): Promise<string> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    req.on("data", (chunk: Buffer) => chunks.push(chunk));
    req.on("end", () => resolve(Buffer.concat(chunks).toString("utf8")));
    req.on("error", reject);
  });
}

function handleTool(tool: string, input: ToolInput): { status: number; payload: unknown } {
  const servedAt = new Date().toISOString();
  switch (tool) {
    case "ping":
      return {
        status: 200,
        payload: { tool: "ping", status: "ok", echo: input, servedAt }
      };
    case "premium.search": {
      const query = typeof input.query === "string" ? input.query : "";
      return {
        status: 200,
        payload: {
          tool: "premium.search",
          query,
          results: [
            {
              title: "x402 payment challenges for MCP tools",
              url: "https://example.com/x402-mcp",
              snippet: "How HTTP 402 challenges gate paid MCP tool calls on Solana."
            },
            {
              title: "Settling SPL token payments on devnet",
              url: "https://example.com/spl-devnet-settlement",
              snippet: "Verifying SPL transfers with getTransaction token balance deltas."
            },
            {
              title: "Receipts and replay protection for agent payments",
              url: "https://example.com/agent-payment-receipts",
              snippet: "Why every settled tool call gets a receipt and a one-time tx signature."
            }
          ],
          servedAt
        }
      };
    }
    case "premium.codegen": {
      const language = typeof input.language === "string" ? input.language : "ts";
      return {
        status: 200,
        payload: {
          tool: "premium.codegen",
          language,
          code: `// generated by example-server\nexport function greet(name: string): string {\n  return \`hello, \${name}\`;\n}\n`,
          servedAt
        }
      };
    }
    default:
      return { status: 404, payload: { error: "unknown_tool" } };
  }
}

const server = http.createServer(async (req, res) => {
  const url = req.url ?? "/";

  if (req.method === "GET" && url === "/healthz") {
    writeJSON(res, 200, { status: "ok", service: "example-server" });
    return;
  }

  if (req.method === "POST" && url === "/mcp") {
    if (gatewayKey !== "" && req.headers["x-gateway-key"] !== gatewayKey) {
      writeJSON(res, 401, { error: "unauthorized" });
      return;
    }

    let parsed: { tool?: unknown; input?: unknown };
    try {
      parsed = JSON.parse(await readBody(req)) as { tool?: unknown; input?: unknown };
    } catch {
      writeJSON(res, 400, { error: "invalid_json" });
      return;
    }

    const tool = typeof parsed.tool === "string" ? parsed.tool : "";
    if (tool === "") {
      writeJSON(res, 400, { error: "tool_required" });
      return;
    }
    const input: ToolInput =
      parsed.input !== null && typeof parsed.input === "object" && !Array.isArray(parsed.input)
        ? (parsed.input as ToolInput)
        : {};

    const requestId = String(req.headers["x-gateway-request-id"] ?? "");
    const { status, payload } = handleTool(tool, input);
    console.log(
      `[example-server] tool=${tool} status=${status} requestId=${requestId || "-"} at=${new Date().toISOString()}`
    );
    writeJSON(res, status, payload);
    return;
  }

  writeJSON(res, 404, { error: "not_found" });
});

server.listen(port, () => {
  console.log(`example-server listening on :${port} (gateway key ${gatewayKey ? "required" : "not required"})`);
});
