/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardToolsRouteImport } from './routes/dashboard.tools'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReceiptsRouteImport } from './routes/dashboard.receipts'
import { Route as DashboardFailedRouteImport } from './routes/dashboard.failed'
import { Route as DashboardRequestsRequestIdRouteImport } from './routes/dashboard.requests.$requestId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardToolsRoute = DashboardToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReceiptsRoute = DashboardReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFailedRoute = DashboardFailedRouteImport.update({
  id: '/failed',
  path: '/failed',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRequestsRequestIdRoute =
  DashboardRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/failed': typeof DashboardFailedRoute
  '/dashboard/receipts': typeof DashboardReceiptsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tools': typeof DashboardToolsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/requests/$requestId': typeof DashboardRequestsRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/failed': typeof DashboardFailedRoute
  '/dashboard/receipts': typeof DashboardReceiptsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tools': typeof DashboardToolsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/requests/$requestId': typeof DashboardRequestsRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/failed': typeof DashboardFailedRoute
  '/dashboard/receipts': typeof DashboardReceiptsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tools': typeof DashboardToolsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/requests/$requestId': typeof DashboardRequestsRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/failed'
    | '/dashboard/receipts'
    | '/dashboard/settings'
    | '/dashboard/tools'
    | '/dashboard/'
    | '/dashboard/requests/$requestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/failed'
    | '/dashboard/receipts'
    | '/dashboard/settings'
    | '/dashboard/tools'
    | '/dashboard'
    | '/dashboard/requests/$requestId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/failed'
    | '/dashboard/receipts'
    | '/dashboard/settings'
    | '/dashboard/tools'
    | '/dashboard/'
    | '/dashboard/requests/$requestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tools': {
      id: '/dashboard/tools'
      path: '/tools'
      fullPath: '/dashboard/tools'
      preLoaderRoute: typeof DashboardToolsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/receipts': {
      id: '/dashboard/receipts'
      path: '/receipts'
      fullPath: '/dashboard/receipts'
      preLoaderRoute: typeof DashboardReceiptsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/failed': {
      id: '/dashboard/failed'
      path: '/failed'
      fullPath: '/dashboard/failed'
      preLoaderRoute: typeof DashboardFailedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/requests/$requestId': {
      id: '/dashboard/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/dashboard/requests/$requestId'
      preLoaderRoute: typeof DashboardRequestsRequestIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardFailedRoute: typeof DashboardFailedRoute
  DashboardReceiptsRoute: typeof DashboardReceiptsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardToolsRoute: typeof DashboardToolsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardRequestsRequestIdRoute: typeof DashboardRequestsRequestIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFailedRoute: DashboardFailedRoute,
  DashboardReceiptsRoute: DashboardReceiptsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardToolsRoute: DashboardToolsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardRequestsRequestIdRoute: DashboardRequestsRequestIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
